In [12]:
import pandas as pd

df_BC = pd.read_excel(r"C:\Users\DanielGP\OneDrive - Caja de Compensacion Familiar de Antioquia COMFAMA\Tendencias\Personal\Especialización\MATRICULA 10 DICIEMBRE.xlsx")
df_BC.head()

,id_participante,ESTADO,TIPO_DOCUMENTO,IDENTIFICACION,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,EDAD_PARTICIPANTE,...,PARENTESCO_QUIEN_COMPARTE,TIPO_DOCUMENTO_FAMILIAR,FAMILIARES.ID_PARTICIPANTE,FAMILIARES.IDENTIFICACION_PARTICIPANTE,FAMILIARES.FECHA_RETIRO,FAMILIARES.EDAD_PARTICIPANTE,FAMILIARES.NOMBRE_COMUNA_FAMILIAR,FAMILIARES.BARRIO_FAMILIAR,FAMILIARES.CORREGIMIENTO_FAMILIAR,FAMILIARES.VEREDA_FAMILIAR
0,749076,RETIRADO,REGISTRO CIVIL NUIP,1017281872,AAIZETH,NaN,ESCOBAR,ALVAREZ,2021-09-21,3,...,NaN,REGISTRO CIVIL NUIP,749076,1017281872,2024-02-15,33.0,VILLA HERMOSA,SUCRE,NaN,NaN
1,795533,ACTIVO,REGISTRO CIVIL NUIP,1021810491,AALIYAH,SKY,CHAVERRA,MARTINEZ,2022-12-09,2,...,NaN,REGISTRO CIVIL NUIP,795533,1021810491,NaN,25.0,BELEN,HONDONADA,NaN,NaN
2,767354,ACTIVO,PERMISO POR PROTECCION TEMPORAL,7908770,AARAN,JOSE,QUILOTTE,LUGO,2022-08-12,2,...,NaN,PERMISO POR PROTECCION TEMPORAL,767354,7908770,2024-04-30,45.0,VILLA HERMOSA,EL PINAL,NaN,NaN
3,737262,RETIRADO,REGISTRO CIVIL NUIP,1015198564,AARON,ALEJANDRO,GUERRERO,ZAMBRANO,2022-02-10,2,...,NaN,REGISTRO CIVIL NUIP,737262,1015198564,2024-09-20,28.0,VILLA HERMOSA,SUCRE,NaN,NaN
4,702959,ACTIVO,PERMISO POR PROTECCION TEMPORAL,7212038,AARON,ALEJANDRO,QUIÑONES,AGUILAR,2019-09-30,5,...,NaN,PERMISO POR PROTECCION TEMPORAL,702959,7212038,2024-05-01,26.0,SAN JAVIER,JUAN XXIII - LA QUIEBRA,NaN,NaN

In [14]:
df_BC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68247 entries, 0 to 68246
Columns: 132 entries, id_participante to FAMILIARES.VEREDA_FAMILIAR
dtypes: datetime64[ns](3), float64(23), int64(10), object(96)
memory usage: 68.7+ MB

In [13]:
df_BC.describe()

,id_participante,FECHA_NACIMIENTO,EDAD_PARTICIPANTE,ESTRATO,COMUNA,BARRIO,CORREGIMIENTO,VEREDA,FECHA_MATRICULA,FECHA_RETIRO,...,FAMILIARES.ID_FAMILIAR,EDAD_FAMILIAR,CODIGO_CUENTAME,ID_CONTRATO,ID_SEDE-2,ID_CORREGIMIENTO_SEDE,ID_FAMILIAR,PARENTESCO_QUIEN_COMPARTE,FAMILIARES.ID_PARTICIPANTE,FAMILIARES.EDAD_PARTICIPANTE
count,68247.000000,68247,68247.000000,67923.000000,57899.000000,57579.000000,10154.000000,10085.000000,68247,17025,...,68244.000000,56424.000000,6.139700e+04,68247.000000,68247.000000,10291.000000,66748.000000,0.0,68247.000000,56407.000000
mean,736394.106173,2017-12-01 04:27:42.877489408,6.542412,1.904863,7.459317,775.911565,71.021568,7135.905900,2024-06-24 14:02:55.023078144,2024-07-22 21:31:28.493392128,...,684658.272478,30.422887,3.409265e+11,1867.763902,1020.547218,69.756098,682914.167900,NaN,736394.106173,30.422430
min,165.000000,1975-02-14 00:00:00,0.000000,1.000000,1.000000,0.000000,13.000000,1316.000000,2024-01-15 00:00:00,2024-01-25 00:00:00,...,166.000000,0.000000,5.001112e+10,1803.000000,3.000000,50.000000,166.000000,NaN,165.000000,0.000000
25%,715311.000000,2019-10-03 00:00:00,2.000000,1.000000,3.000000,310.000000,60.000000,6097.000000,2024-05-01 00:00:00,2024-05-16 00:00:00,...,688102.500000,25.000000,5.001115e+10,1855.000000,423.000000,60.000000,687282.250000,NaN,715311.000000,25.000000
50%,757804.000000,2021-01-30 00:00:00,3.000000,2.000000,7.000000,712.000000,70.000000,7085.000000,2024-05-24 00:00:00,2024-08-01 00:00:00,...,741759.500000,29.000000,5.001001e+11,1874.000000,1100.000000,70.000000,740654.500000,NaN,757804.000000,29.000000
75%,778452.500000,2022-10-04 00:00:00,5.000000,2.000000,9.000000,914.000000,80.000000,8000.000000,2024-09-02 00:00:00,2024-10-01 00:00:00,...,763696.250000,34.000000,5.001001e+11,1881.000000,1593.000000,80.000000,762680.250000,NaN,778452.500000,34.000000
max,796006.000000,2024-12-04 00:00:00,49.000000,7.000000,90.000000,91602.000000,90.000000,9084.000000,2024-12-10 00:00:00,2024-12-10 00:00:00,...,795851.000000,87.000000,5.001001e+11,1887.000000,1947.000000,90.000000,780267.000000,NaN,796006.000000,87.000000
std,73025.291945,NaN,9.230637,0.787116,7.643404,1510.073762,10.691414,1049.794595,NaN,NaN,...,148498.136005,8.197473,2.151901e+11,16.254615,621.764391,10.243336,149153.085366,NaN,73025.291945,8.197367

In [16]:
df_BC.isna().sum().sort_values(ascending=False)

MUNICIPIO_DESPLAZAMIENTO      68247
PARENTESCO_QUIEN_COMPARTE     68247
PESO_GESTACION                68247
CAJA_COMPENSACION_FAMILIAR    68197
NUMERO_DE_VACUNAS             68053
                              ...
FECHA_MATRICULA                   0
PRESTADOR_ID                      0
ID_SEDE-2                         0
ID_CONTRATO                       0
FAMILIARES.ID_PARTICIPANTE        0
Length: 132, dtype: int64